//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificates_For_School
    {
        public int Serial_Num { get; set; }
        public Nullable<int> Class_Code { get; set; }
        public Nullable<int> Certificates_Code { get; set; }
        public Nullable<int> Code_School { get; set; }
        public System.DateTime Update_Date { get; set; }
        public System.DateTime Add_Date { get; set; }
    
        public virtual Certificate Certificate { get; set; }
        public virtual Class Class { get; set; }
        public virtual School School { get; set; }
    }
}
