//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Behaviors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Class_Behaviors()
        {
            this.Class_Behaviors_And_Actions = new HashSet<Class_Behaviors_And_Actions>();
        }
        public int Behavior_Code { get; set; }
        public string Behavior_Name { get; set; }
        public double Percentage_Of_Final_Mark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class_Behaviors_And_Actions> Class_Behaviors_And_Actions { get; set; }
    }
}
