//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Behaviors_And_Actions
    {
        public int Serial_Num { get; set; }
        public Nullable<int> Code_School { get; set; }
        public Nullable<int> Class_Code { get; set; }
        public Nullable<int> Behavior_Code { get; set; }
    
        public virtual Class_Behaviors Class_Behaviors { get; set; }
        public virtual Class Class { get; set; }
        public virtual School School { get; set; }
    }
}
