//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade_Categories_For_School
    {
        public int Categorie_Code { get; set; }
        public int Mark { get; set; }
        public int From_Mark { get; set; }
        public int TO_Mark { get; set; }
        public string Mark_Name { get; set; }
    }
}
