//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class schoolDBEntities : DbContext
    {
        public schoolDBEntities()
            : base("name=schoolDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Certificate> Certificates { get; set; }
        public virtual DbSet<Certificates_For_School> Certificates_For_School { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Class_Behaviors> Class_Behaviors { get; set; }
        public virtual DbSet<Class_Behaviors_And_Actions> Class_Behaviors_And_Actions { get; set; }
        public virtual DbSet<Class> Classes { get; set; }
        public virtual DbSet<Educational_Level> Educational_Level { get; set; }
        public virtual DbSet<Exams_For_Students> Exams_For_Students { get; set; }
        public virtual DbSet<Grade_Categories_For_School> Grade_Categories_For_School { get; set; }
        public virtual DbSet<Institution> Institutions { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Student_Grade_Score> Student_Grade_Score { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<Subjects_For_Classes> Subjects_For_Classes { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Teachers_For_Classes> Teachers_For_Classes { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<Tests_For_Student> Tests_For_Student { get; set; }
    }
}
