//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subjects_For_Classes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Subjects_For_Classes()
        {
            this.Exams_For_Students = new HashSet<Exams_For_Students>();
            this.Student_Grade_Score = new HashSet<Student_Grade_Score>();
            this.Tests = new HashSet<Test>();
            this.Tests_For_Student = new HashSet<Tests_For_Student>();
        }
    
        public int Serial_Num { get; set; }
        public Nullable<int> Class_Code { get; set; }
        public Nullable<int> ID_Teacher { get; set; }
        public Nullable<int> Subjects_Code { get; set; }
        public Nullable<int> Semester_Code { get; set; }
        public Nullable<int> Educational_Level_Code { get; set; }
        public System.DateTime Update_Date { get; set; }
        public System.DateTime Add_Date { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Educational_Level Educational_Level { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exams_For_Students> Exams_For_Students { get; set; }
        public virtual Semester Semester { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_Grade_Score> Student_Grade_Score { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Test> Tests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tests_For_Student> Tests_For_Student { get; set; }
    }
}
