//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers_For_Classes
    {
        public int Serial_Num { get; set; }
        public Nullable<int> Class_Code { get; set; }
        public Nullable<int> ID_Teacher { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
