//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests_For_Student
    {
        public int Serial_Num { get; set; }
        public Nullable<int> Code_Subjects_For_Classes { get; set; }
        public Nullable<int> Tests_Code { get; set; }
        public Nullable<int> ID_Student { get; set; }
        public int Mark { get; set; }
        public System.DateTime Update_Date { get; set; }
        public System.DateTime Add_Date { get; set; }
    
        public virtual Student Student { get; set; }
        public virtual Subjects_For_Classes Subjects_For_Classes { get; set; }
        public virtual Test Test { get; set; }
    }
}
